### ISSUE TITLE
Debugging connection problem (cannot connect to server)

### ISSUE THREAD

**Issue by kinnla** [benetech/Martus-Project#1]
Hi,
I am testing Martus 5.1.1 on OSX. I had created two incidents in January and synced them to your default server. Now I changed those incidents, but cannot connect to the server. In the settings, 54.72.26.74 is given as server IP. The server is not down (I can ping it).

How to do further debugging? are there logfiles created by Martus that I can evaluate?

I tried to switch on/off tor, but no effect.
Best, kinnla

**Comment by kinnla** [comment]
I checked out your documentation and you recommend a traceroute. Here it is:
Traceroute se ha iniciado…

traceroute to 54.72.26.74 (54.72.26.74), 64 hops max, 72 byte packets
 1  \* \* *
 2  83-169-180-222-isp.superkabel.de (83.169.180.222)  71.024 ms  9.959 ms  8.550 ms
 3  ip5886c231.dynamic.kabel-deutschland.de (88.134.194.49)  8.650 ms  9.001 ms  20.948 ms
 4  ip5886ca5e.dynamic.kabel-deutschland.de (88.134.202.94)  8.596 ms  19.762 ms  7.609 ms
 5  ip5886ca0d.dynamic.kabel-deutschland.de (88.134.202.13)  53.718 ms  87.190 ms  103.444 ms
 6  ip5886ca99.dynamic.kabel-deutschland.de (88.134.202.153)  70.451 ms  30.350 ms  35.565 ms
 7  decix2.amazon.com (80.81.195.152)  145.317 ms  17.129 ms  17.149 ms
 8  \* \* *
 9  \* \* *
10  \* \* *
11  178.236.0.225 (178.236.0.225)  40.934 ms  42.754 ms  44.209 ms
12  178.236.0.206 (178.236.0.206)  63.937 ms  39.065 ms  39.860 ms
13  178.236.0.213 (178.236.0.213)  38.607 ms  92.053 ms  37.281 ms
14  ec2-54-72-26-74.eu-west-1.compute.amazonaws.com (54.72.26.74)  36.009 ms  35.482 ms  37.931 ms

**Comment by johnhbenetech** [comment]
Hi kinnla,

There seems to be an issue affecting Martus with the newest version of Java on OSX.

 We currently recommend installing Java SDK v66 until we can repair the issue on our side.

The SDK is available here: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jdk-8u66-oth-JPR

**Comment by kinnla** [comment]
Hi John, I am running Java 8-60:

> $ java -version
> java version "1.8.0_60"
> Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
> Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

and don't remember having it updated since I created the Martus-records in January. There has been an OS-X update (10.11.3), maybe the problem is related to this update?

**Comment by johnhbenetech** [comment]
Hmm.. we have several machines running successfully with 10.11.3. One option is to run Martus with debugging output and send us some of the logs. 

Ctrl+Click the Martus icon, select 'Show Package Contents'

Open the JavaAppLauncher under Contents>MacOS>JavaAppLauncher

This should give some detailed information about which Java version Martus is using, as well as any debug information from the server connection failure.

You can also send us info to martus@benetech.org for direct contact: https://pgp.mit.edu/pks/lookup?op=get&search=0xD886DA5938E22FA4

**Comment by kinnla** [comment]
Hi John, You are right, Martus starts with Java 8_71. I had the hell of several JDKs on my system without knowing in the past, and now I am back again. This time it was hiding as Java-Browser Plugin. I deleted the plugin and started Martus again. I expected it to start from my system default java, but it did not find it, and did not start at all. Does Martus require its Java to be the type of a plugin?

By the way, the Exception I got with Java 8_71 was a 

> java.security.cert.CertificateException: Certificates does not conform to algorithm constraints

Probably that's the same problem that you already identified.

**Comment by johnhbenetech** [comment]
Unfortunately getting a specific Java version to run on OSX is a bit of an ordeal. The best recommendation I can make is to uninstall all the existing Java versions and then reinstall the JDK file above (even if you think you already installed it). There are a lot of symlinks and variables that get updated by Java, and it seems reinstalling can help make sure they are in sync.

For example, what I did on my machine:

sudo -rm -fr /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin
sudo -rm -fr /Library/PreferencePanes/JavaControlPanel.prefpane
sudo -rm -rf /Library/Java/JavaVirtualMachines/*

After this process is completed, you can download and install the above JDK (1.8.0_66). After install things should hopefully be configured correctly. Let us know if you still are having issues!

**Comment by kinnla** [comment]
Hi John, thanks for the suggestion! It seems that the JavaAppLauncher contained in the Martus.app bundle requires a Java-Plugin. I did not find any way to configure it using the System java (1.8.0_60). So as a workaround I cloned the repository and started Martus via the Eclipse Project, which went very smooth.As a bonus, Martus supports my retina now :-)
