### ISSUE TITLE
Debugging send to default or send to contact problem

### ISSUE THREAD

**Issue by gdecourcy** [benetech/Martus-Project#2]
Hi - I'm using Martus on Mac but have also tried on PC but cannot get records to send to other contacts. Neither by default or by selecting the contact to send to on each individual record. Does anyone know what I'm doing wrong? I don't get any error message - just nothing is received on the other account. Thanks

**Comment by johnhbenetech** [comment]
Hi gdecourcy,

One thing to check is to make sure you are doing the following:
- Edit a record, add the contact using the icon in the upper right
- Make sure the contact name of fingerprint appears in the "To:" field
- At the bottom right of the record screen, there should be a button labeled 'Share'
- Hitting the share button is what actually sends the record to the contact.

We realize the Share vs. Save user experience is a bit confusing right now, so we are working to adjust it in a future release. Let me know if this helps, if not we can try some other things!

You can also email martus@benetech.org

**Comment by gdecourcy** [comment]
Hi John,

Thank you! Can't believe it was something so simple!

Thanks,
Georgia

Georgia de Courcy Wheeler
Projects & Communications Officer
Beyond Borders Scotland

​A:
14 Albany Street
​, Edinburgh, EH1 3QB​
​
T: +44(0)131 557 7775
M: +44(0)7807 217 660
E: gdecourcy@beyondbordersscotland.com
W: www.beyondbordersscotland.com

Please consider the environment before printing this email or any
attachments.

**Comment by gdecourcy** [comment]
Hi John

Hoping you can help with this one. I have exported 500 records from Martus.
150 of them have attachments. But when I try to import them to Martus on a
different computer (the old one cannot connect to the internet anymore) the
attachments are separate from the record and I can't work out what I'm
doing wrong!

Thanks in advance
Georgia

Georgia de Courcy Wheeler
Projects & Communications Officer
Beyond Borders Scotland

​A:
14 Albany Street
​, Edinburgh, EH1 3QB​
​
T: +44(0)131 557 7775
M: +44(0)7807 217 660
E: gdecourcy@beyondbordersscotland.com
W: www.beyondbordersscotland.com

Please consider the environment before printing this email or any
attachments.

**Comment by tmalik25** [comment]
Hi Georgia, I am the new Product Manager for Martus. John forwarded me your request and I agree that  importing attachments could be confusing. 

For your scenario, I'd recommend backing up your key and using the Encrypted export. You can then use that key to setup Martus on another computer and import the records. I have described this in two parts below. 

However, if you want to setup a new account on your computer and not use the same key, please let me know and I'll send the instructions for that.

# 

_**PART A**: Backing up your key and exporting encrypted records_
Steps for backing up your key: 
1. Choose Account > Key Backup [Top Right Corner]
2. Select - Export Password Protected Key. 
3. In the Backup Key File dialog box, navigate to your removable media device (e.g., USB or  CD), or your network drive.

Below are the steps for encrypted export: 
1. Select the records that you want to export
2. Click on "Export records button near the bottom left corner"
3. Select the folder and click Export - Don't uncheck the Encrypted option.

_**PART B**: Adding backup key to new computer and importing encrypted records_
Restoring account with the backed up key
1. Start Martus.
2. Select the Restore Account tab in the Martus Signin dialog box. 
3. Select Restore account from backup key file. 
4. Read the informational dialog box, and click OK. 
5. Find the file on your hard-disk/network-drive or insert the floppy disk (or other removable  media) that contains the file and navigate to it, and click OK.  

Once the above is done, you can then import the encrypted records - and the attachments will be imported as well. 

**RISKS**: Anyone could use your backup key to unencrypt your records. So, I’d recommend being careful with the backup version of the key.

Best
Tarun

**Comment by gdecourcy** [comment]
Hi Tarun,

Thanks for this but yes it is a new account on a new computer - not using the backup key. I've exported the records but when I add them to the new account the attachments are separate from the records - like there's two records 1 with the record information and 1 with the attachments.

Thanks for your help
Georgia

**Comment by tmalik25** [comment]
Georgia, What you mentioned is an issue in Martus and we will work on fixing it - that is if you export unencrypted records, all the records are exported to one folder along with all the attachments (sorry!). 

If you don't want to use your existing account, there is one more option (other than what I described in the previous comment). 
1. Create a new account on a computer that has internet access 
2. Share your records with that account 
3. Use the backup key for that new account to setup Martus on your computer with no internet access.

If you can wait 1-2 weeks, we might be able release an update (along with several other updates that we are working on).

I'd also be glad to setup a call - if that's helpful.

**Comment by gdecourcy** [comment]
Thanks - I was able to do it with the first suggestion of exporting the key.
But how can I add all the records at once? Rather than one at a time

**Comment by tmalik25** [comment]
Great. And an update is coming very soon which would allow you to add multiple records at once. Until then.. it's one at a time (sorry!)

**Comment by gdecourcy** [comment]
Is there a quicker way of sharing files with another Martus user other than doing each one individually?

**Comment by tmalik25** [comment]
Georgia, I hate to disappoint you again but no - right now you'll have to share them individually. Yet again, fixes are coming.. so there is light at the end of the tunnel :)
